config/routes.rb
Rails.application.routes.draw do
  root to: "movies#index"
  resources :showtimes, only: [:index, :new, :create, :destroy]
  resources :auditoria, only: [:new, :create]
  resources :orders, only: [:index, :new, :create]
  resources :movies, only: [:index, :new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/auditorium.rb
class Auditorium < ApplicationRecord
  has_many :showtimes

  validates :room, :capacity, :presence => true, numericality: { only_integer: true }
  validates :room, uniqueness: true

end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :showtimes

  validates :title, :runtime, :presence => true
  validates :runtime, numericality: { only_integer: true}

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :showtime

  validates :name, :email, :credit_card, :expiration, :total, :showtime_id, :presence => true
  validates :credit_card, numericality: { only_integer: true}
  validate :credit_card_length
  validate :expiration_date

  def self.movie_search(criteria)
    orders = Order.all
    by_movie = []
    orders.each do |order|
      movie = order.showtime.movie.title
      if movie == criteria
        by_movie << order
      end
    end
    by_movie
  end

  def update_tickets_sold
    self.showtime.tickets_sold +=1
    self.showtime.save
  end

  def credit_card_length
    if self.credit_card.length != 16
      errors.add(:credit_card, "length must be 16 digits long")
    end
  end

  def expiration_date
    if self.expiration != nil
      if self. expiration < Date.today
        errors.add(:expiration_date, "must be greater than today")
      end
    end
  end


end

app/models/showtime.rb
class Showtime < ApplicationRecord
  belongs_to :movie
  belongs_to :auditorium

  validates :showdate, :start_time, :end_time, :tickets_sold, :movie_id, :auditorium_id, :presence => true
  validate :overlap

  def sold_out?()
    self.tickets_sold == self.auditorium.capacity
  end

  def past_date?()
    self.start_time < DateTime.now
  end

  def overlap()
    showtimes = Showtime.where(auditorium_id: self.auditorium_id).where.not(id: self.id)
    if showtimes.size >= 1
      if (showtimes.where("end_time > ?", self.start_time).size >= 1 && showtimes.where("end_time < ?", self.end_time).size >= 1) || (showtimes.where("start_time > ?", self.start_time).size >= 1 && showtimes.where("start_time < ?", self.end_time).size >= 1) || (showtimes.where("start_time < ?", self.start_time).size >= 1 && (showtimes.where("end_time > ?", self.end_time).size >= 1))
          errors.add(:timing_issue, "The start or end time conflicts with an existing showtime. Try again")
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/auditoria_controller.rb
class AuditoriaController < ApplicationController

  def new
    @auditorium = Auditorium.new
    render :new
  end

  def create
   @auditorium = Auditorium.new(auditorium_params)
    if @auditorium.save
      redirect_to showtimes_path
    else
      @errors = @auditorium.errors.full_messages
      render :new
    end
  end

  def auditorium_params
    params.require(:auditorium).permit(:room, :capacity)
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def index
    @movies = Movie.all
    render :index
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
       redirect_to showtimes_path
    else
      @errors = @movie.errors.full_messages
      render :new
    end
  end

  def movie_params
    params.require(:movie).permit(:title, :runtime)
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
    if params[:search]
      @orders = Order.movie_search(params[:search])
    else
      @orders = Order.all
    end
  end

  def new
    @order = Order.new
    @showtime = Showtime.find(params[:showtime])
    render :new
  end

  def create
    @showtime = Showtime.find(order_params[:showtime_id])
    @order = Order.new(order_params)
    if @order.save
      @order.update_tickets_sold
      OrderMailer.order_confirmation(@order).deliver
      redirect_to movies_path
    else
      @errors = @order.errors.full_messages
      render :new
    end
  end

  def order_params
    params.require(:order).permit(:name, :email, :credit_card, :expiration, :total, :showtime_id)
  end

end

app/controllers/showtimes_controller.rb
class ShowtimesController < ApplicationController

  def index
    @showtimes = Showtime.all.order(:showdate)
    render :index
  end

  def new
    @showtime = Showtime.new
  end

  def create
   @showtime = Showtime.new(showtime_params)
    if @showtime.save
      redirect_to movies_path
    else
      @errors = @showtime.errors.full_messages
      render :new
    end
  end

  def destroy
    @showtime = Showtime.find(params[:showtime])
    @showtime.destroy
    redirect_to showtimes_path
  end

  def showtime_params
    params.require(:showtime).permit(:showdate, :start_time, :end_time, :price, :tickets_sold, :movie_id, :auditorium_id)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper

  def format_fulldate(date)
    date.strftime("%m/%d/%Y at %I:%M%p")
  end

  def format_dateonly(date)
    date.strftime("%m/%d/%Y")
  end

  def format_timeonly(date)
    date.strftime("%I:%M%p")
  end



end

app/helpers/auditoria_helper.rb
module AuditoriaHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/showtimes_helper.rb
module ShowtimesHelper


end

app/views/auditoria/new.html.erb
<div class="page">
  <h1>Create Auditorium</h1>

  <% if @errors %>
    <div class="errors">
      <%= render partial: "partials/errors", locals: { errors: @errors } %>
    </div>
  <% end %>

  <div class="form">
    <%= form_for @auditorium, {action: "create"} do |f| %>
      <fieldset>
        <div class="form-group">
          Room Number <%= f.number_field :room, class: "form-control col-sm-6" %>
        </div>
        <div class="form-group">
          Capacity <%= f.number_field :capacity, class: "form-control col-sm-6" %>
        </div>
        <%= f.submit "Create", class: "btn btn-primary" %>
        <%= link_to "Cancel", showtimes_path %>
      </fieldset>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lp v2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <ul class="nav navbar-nav">
          <li class="active"><%= link_to "Home", movies_path %></li>
          <li><%= link_to "Admin", showtimes_path %></li>
        </ul>
      </div>
    </nav>
    <div class="banner">
      <img src="<%= asset_path( 'bkg.png' ) %>" alt="banner" width="800" height="300" padding-top: 20px; >
    </div>
    <%= yield %>
  </body>
</html>

app/views/movies/index.html.erb
<div class="page">
  <div>
    <%= link_to "Create Showtime", new_showtime_path %>
  </div>

  <h1>All Movie Showtimes</h1>

  <div>
    <ul class="list-group">
      <% @movies.each do |movie| %>
        <li >
          <p class="movie "><%= movie.title %>, <%= movie.runtime %> minutes</p>
          <ul class="list-group">
             <% movie.showtimes.each do |showtime| %>
              <% if !showtime.sold_out? && !showtime.past_date? %>
            <li class="list-group-item">
               <p><%= format_fulldate(showtime.start_time) %> --
                <%= link_to "Purchase Ticket", new_order_path(:showtime =>showtime) %></p>
            </li>
              <% end %>
            <% end %>
          </ul>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/movies/new.html.erb
<div class="page">
  <h1>Create Movie</h1>

  <% if @errors %>
    <div class="errors">
      <%= render partial: "partials/errors", locals: { errors: @errors } %>
    </div>
  <% end %>

  <div >
    <%= form_for @movie, {action: "create"} do |f| %>
      <fieldset>
        <div class="form-group">
          Movie Title <%= f.text_field :title, class: "form-control col-sm-6" %>
        </div>
        <div class="form-group">
          Runtime <%= f.number_field :runtime, class: "form-control col-sm-6" %>
        </div>
          <%= f.submit "Create", class: "btn btn-primary" %>
        <%= link_to "Cancel", showtimes_path %>
      </fieldset>
    <% end %>
  </div>
</div>

app/views/orders/index.html.erb
<div class="page">
  <h1>Orders</h1>

  <div class="form-group">
    <%= form_tag(orders_path, method: "get") do %>
      <%= label_tag(:q, "Search By Movie Title:") %>
      <%= text_field_tag :search, params[:search] %>
        <%= submit_tag "Search", :name => nil, class: "btn btn-primary btn-sm" %>
    <% end %>
    <div >
       <%= form_tag(orders_path, method: "get") do %>
          <%= submit_tag "Refresh", :name => nil, class: "btn btn-default btn-sm" %>
      <% end %>
    </div>
  </div>


  <div>
    <table class="table">
      <tr>
         <th>Order Number</th>
         <th>Order Date</th>
         <th>Order Total</th>
         <th>Movie Title</th>
      </tr>
      <% @orders.each do |order| %>
        <tr>
          <td><%= order.id %></td>
          <td><%= order.created_at %></td>
          <td><%= order.total %></td>
          <td><%= order.showtime.movie.title %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/orders/new.html.erb
<div class="page">
  <h1>Purchase Ticket</h1>

  <% if @errors %>
    <div class="errors">
      <%= render partial: "partials/errors", locals: { errors: @errors } %>
    </div>
  <% end %>

  <div class="ticket-info">
    <p>Movie: <%= @showtime.movie.title %></p>
    <p>Showtime: <%= format_fulldate(@showtime.start_time) %> - <%= format_timeonly(@showtime.end_time) %></p>
    <p>Total: $<%= @showtime.price %></p>
  </div>

  <div class="">
    <%= form_for @order, {action: "create"} do |f| %>
      <fieldset>
        <div class="form-group">
          Name: <%= f.text_field :name, class: "form-control col-sm-6" %>
        </div>
        <div class="form-group">
          Email: <%= f.email_field :email, class: "form-control col-sm-6" %>
        </div>
        <div class="form-group">
         Credit Card: <%= f.text_field :credit_card, placeholder: "411111111111", class: "form-control col-sm-6" %>
        </div>
        <div class="form-group">
          Expiration: <%= f.date_field :expiration, placeholder: "2017-02-27", class: "form-control col-sm-6" %>
        </div>
        <%= f.hidden_field :showtime_id, value: @showtime.id %>
        <%= f.hidden_field :total, value: @showtime.price %>

          <%= f.submit "Create", class: "btn btn-primary" %>

        <%= link_to "Cancel", movies_path %>
      </fieldset>
    <% end %>
  </div>
</div>

app/views/partials/_errors.html.erb
<ul>
  <% errors.each do |error| %>
    <li><%= error %></li>
  <% end %>
</ul>

app/views/showtimes/index.html.erb
<div class="page">

  <ul class="list-group">
    <li class="list-group-item"><%= link_to "Create Showtime", new_showtime_path %></li>
    <li class="list-group-item"><%= link_to "Create Auditorium", new_auditorium_path %></li>
    <li class="list-group-item"><%= link_to "Create Movie", new_movie_path %></li>
    <li class="list-group-item"><%= link_to "Orders", orders_path %></li>
   </ul>

  <div>
    <h2>All Showtimes</h2>
    <table class="table">
      <tr>
         <th>Movie</th>
         <th>Auditorium</th>
         <th>Date</th>
         <th>Start Time</th>
         <th>End Time</th>
         <th>Delete Showing</th>
      </tr>
      <% @showtimes.each do |showtime| %>
        <tr>
          <td><%= showtime.movie.title %></td>
          <td><%= showtime.auditorium.room %></td>
          <td><%= format_dateonly(showtime.showdate) %></td>
          <td><%= format_timeonly(showtime.start_time) %></td>
          <td><%=format_timeonly(showtime.end_time) %></td>
          <td><%= link_to "Delete", showtime_path(showtime.id, :showtime =>showtime), :method => :delete %></td>
          </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/showtimes/new.html.erb
<div class="page">
  <h1>Create Showtime</h1>

  <% if @errors %>
    <div class="errors">
      <%= render partial: "partials/errors", locals: { errors: @errors } %>
    </div>
  <% end %>

  <div >
    <%= form_for @showtime, {action: "create"} do |f| %>
      <fieldset>
        <div class="form-group">
          Show Date <%= f.date_field :showdate, class: "form-control col-sm-6" %>
        </div>
        <div class="form-group">
          Start Time <%= f.datetime_field :start_time, class: "form-control col-sm-6" %>
        </div>
        <div class="form-group">
          End Time <%= f.datetime_field :end_time, class: "form-control col-sm-6" %>
        </div>
        <div class="form-group">
          Movies <p><%= f.collection_select :movie_id, Movie.all, :id, :title, class: "form-control col-sm-6" %></p>
        </div>
        <div class="form-group">
          Ticket Price <%= f.number_field :price, class: "form-control col-sm-6" %>
        </div>
        <div class="form-group">
          Tickets Sold <%= f.number_field :tickets_sold, value: 0, class: "form-control col-sm-6" %>
        </div>
        <div class="form-group">
          Auditorium Room <p><%= f.collection_select :auditorium_id, Auditorium.all, :id, :room, class: "form-control col-sm-6" %></p>
        </div>
        <%= f.submit "Create", class: "btn btn-primary" %>
        <%= link_to "Cancel", :back %>
      </fieldset>
    <% end %>
  </div>
</div>